services:
  postgres:
    container_name: archetypes-postgres
    networks:
      - proxynet
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "archetypes"
    ports:
      - "127.0.0.1:5432:5432"

networks:
  proxynet:
    name: archetypes-network
