---
server:
  port: 8080
  shutdown: "graceful"
  max-http-request-header-size: "20KB"
management:
  endpoints:
    web:
      exposure:
        include:
        - "health"
  endpoint:
    health:
      probes:
        enabled: true
spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:os-app-template}"
    username: "${POSTGRES_USERNAME:postgres}"
    password: "${POSTGRES_PASSWORD:secret}"
    driver-class-name: "org.postgresql.Driver"
    hikari.poolName: "os-app-template"
  flyway:
    enabled: true
